### ISSUE TITLE
basic streaming demo node.js pgm reports an error  

### ISSUE THREAD

**Issue by priyablue** [plotly/Streaming-Demos#2]

**Comment by etpinard** [comment]
what kind of error?

**Comment by priyablue** [comment]
i want to plot the values taken from serial port ,not from any tabulated
values or predefined values.I need to get a dynamic multi axes graph by
streaming the data and not a fixed graph or a static graph.

On Sun, Aug 30, 2015 at 10:57 PM, Étienne Tétreault-Pinard <
notifications@github.com> wrote:

> what kind of error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/Streaming-Demos/issues/2#issuecomment-136161822>
> .
>



-- 
Warm regards,
Saipriya Mukunthaprabhu,
Junior Research Associate (R&D),
Bluetronics,
Bengaluru, India.

**Comment by chintanp** [comment]
I am trying to achieve the same thing, havent got there yet, though this great post from Adil goes a long way in helping, tell me if you get it done : 

http://adilmoujahid.com/posts/2015/07/practical-introduction-iot-arduino-nodejs-plotly/

**Comment by priyablue** [comment]
Greetings,
          To your kind information i am working with the link you have
listed it above .. i need to do in msp430 ,i ll use two boards with
different plotly tokens generated,with different com ports.But the think is
that when i do it in energia with same requirements i am getting the values
in serial monitor.The samething while doing for plotly i dont get any thing
.. it is automatically stopped .. If you have any idea please do let me
know that ...
                               Thank you

On Fri, Sep 4, 2015 at 7:31 PM, Chintan Pathak <notifications@github.com>
wrote:

> I am trying to achieve the same thing, havent got there yet, though this
> great post from Adil goes a long way in helping, tell me if you get it done
> :
>
>
> http://adilmoujahid.com/posts/2015/07/practical-introduction-iot-arduino-nodejs-plotly/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/Streaming-Demos/issues/2#issuecomment-137745209>
> .
>



-- 
Warm regards,
Saipriya Mukunthaprabhu,
Junior Research Associate (R&D),
Bluetronics,
Bengaluru, India.

**Comment by chintanp** [comment]
While I have not successfully been able to plot multiple traces well, I did manage to run a single stream well in real-time as in the example. Have you tried running a single board ? Did it work well ? What is the code that you are using in your nodejs file ? If serial monitor displays values correctly, it means that your energia code is fine, and you can close energia and leave that. Now try, running the node code, try with this simple code: https://github.com/chintanp/node_serial_uC/blob/master/serial_check.js to check whether your node code reads the serial data properly. It will require you to have node and serial port library (Serialport works only with few versions of node). Change the COM port in the code to your COM port. Then report the error as you get in the output.

**Comment by priyablue** [comment]
OpenCV Error: Unspecified error (File can't be opened for writing!) in load, file /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/contrib/src/facerec.cpp, line 325
Traceback (most recent call last):
  File "face_recog_eigen.py", line 76, in <module>
    recognizer.load_trained_data()
  File "face_recog_eigen.py", line 24, in load_trained_data
    self.model.load('eigen_trained_data.xml')
cv2.error: /build/opencv-ISmtkH/opencv-2.4.9.1+dfsg/modules/contrib/src/facerec.cpp:325: error: (-2) File can't be opened for writing! in function load
 Hi , i dont know what is this error corresponds to? any body help me out

**Comment by priyablue** [comment]
Hi chintanp 
I got the code working for msp430.
